// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Resolve DATABASE_URL — if unset, default to SQLite for local dev convenience.
const dbUrl = (() => {
  try {
    return process.env.DATABASE_URL || env("DATABASE_URL");
  } catch {
    return "file:./prisma/dev.db";
  }
})();

// Dynamically select the schema file based on the DATABASE_URL scheme.
//   file:./prisma/dev.db  → prisma/schema.sqlite.prisma
//   postgresql://...       → prisma/schema.postgresql.prisma
const isSqlite = dbUrl.startsWith("file:");

export default defineConfig({
  schema: isSqlite ? "prisma/schema.sqlite.prisma" : "prisma/schema.postgresql.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
