// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/English.tsx": () => import("../components/mockups/landing/English.tsx"),
  "./components/mockups/landing/Indonesian.tsx": () => import("../components/mockups/landing/Indonesian.tsx"),
  "./components/mockups/landing/Mobile.tsx": () => import("../components/mockups/landing/Mobile.tsx")
};
