/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as ApiSpeciesRouteImport } from './routes/api/species'
import { Route as ApiPetsRouteImport } from './routes/api/pets'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUsersMeRouteImport } from './routes/api/users.me'
import { Route as ApiPetsPetIdRouteImport } from './routes/api/pets.$petId'
import { Route as ApiUsersMeRegisterPetOwnerRouteImport } from './routes/api/users.me.register-pet-owner'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeciesRoute = ApiSpeciesRouteImport.update({
  id: '/api/species',
  path: '/api/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetsRoute = ApiPetsRouteImport.update({
  id: '/api/pets',
  path: '/api/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetsPetIdRoute = ApiPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => ApiPetsRoute,
} as any)
const ApiUsersMeRegisterPetOwnerRoute =
  ApiUsersMeRegisterPetOwnerRouteImport.update({
    id: '/register-pet-owner',
    path: '/register-pet-owner',
    getParentRoute: () => ApiUsersMeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/pets/': typeof PetsIndexRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/pets': typeof PetsIndexRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/pets/': typeof PetsIndexRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/pets/$petId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/pets/'
    | '/api/pets/$petId'
    | '/api/users/me'
    | '/api/users/me/register-pet-owner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/pets/$petId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/pets'
    | '/api/pets/$petId'
    | '/api/users/me'
    | '/api/users/me/register-pet-owner'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/pets/$petId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/pets/'
    | '/api/pets/$petId'
    | '/api/users/me'
    | '/api/users/me/register-pet-owner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPetsRoute: typeof ApiPetsRouteWithChildren
  ApiSpeciesRoute: typeof ApiSpeciesRoute
  ApiVisitsRoute: typeof ApiVisitsRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  PetsIndexRoute: typeof PetsIndexRoute
  ApiUsersMeRoute: typeof ApiUsersMeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/species': {
      id: '/api/species'
      path: '/api/species'
      fullPath: '/api/species'
      preLoaderRoute: typeof ApiSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pets': {
      id: '/api/pets'
      path: '/api/pets'
      fullPath: '/api/pets'
      preLoaderRoute: typeof ApiPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pets/$petId': {
      id: '/api/pets/$petId'
      path: '/$petId'
      fullPath: '/api/pets/$petId'
      preLoaderRoute: typeof ApiPetsPetIdRouteImport
      parentRoute: typeof ApiPetsRoute
    }
    '/api/users/me/register-pet-owner': {
      id: '/api/users/me/register-pet-owner'
      path: '/register-pet-owner'
      fullPath: '/api/users/me/register-pet-owner'
      preLoaderRoute: typeof ApiUsersMeRegisterPetOwnerRouteImport
      parentRoute: typeof ApiUsersMeRoute
    }
  }
}

interface ApiPetsRouteChildren {
  ApiPetsPetIdRoute: typeof ApiPetsPetIdRoute
}

const ApiPetsRouteChildren: ApiPetsRouteChildren = {
  ApiPetsPetIdRoute: ApiPetsPetIdRoute,
}

const ApiPetsRouteWithChildren =
  ApiPetsRoute._addFileChildren(ApiPetsRouteChildren)

interface ApiUsersMeRouteChildren {
  ApiUsersMeRegisterPetOwnerRoute: typeof ApiUsersMeRegisterPetOwnerRoute
}

const ApiUsersMeRouteChildren: ApiUsersMeRouteChildren = {
  ApiUsersMeRegisterPetOwnerRoute: ApiUsersMeRegisterPetOwnerRoute,
}

const ApiUsersMeRouteWithChildren = ApiUsersMeRoute._addFileChildren(
  ApiUsersMeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPetsRoute: ApiPetsRouteWithChildren,
  ApiSpeciesRoute: ApiSpeciesRoute,
  ApiVisitsRoute: ApiVisitsRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  PetsIndexRoute: PetsIndexRoute,
  ApiUsersMeRoute: ApiUsersMeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
