/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetIndexRouteImport } from './routes/vet.index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as HotelIndexRouteImport } from './routes/hotel.index'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as VetSearchRouteImport } from './routes/vet.search'
import { Route as VetReportsRouteImport } from './routes/vet.reports'
import { Route as VetHotelRouteImport } from './routes/vet.hotel'
import { Route as VetAddPetRouteImport } from './routes/vet.add-pet'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { Route as HotelSearchRouteImport } from './routes/hotel.search'
import { Route as HotelReportsRouteImport } from './routes/hotel.reports'
import { Route as HotelHistoryRouteImport } from './routes/hotel.history'
import { Route as HotelGuestsRouteImport } from './routes/hotel/guests'
import { Route as HotelAddPetRouteImport } from './routes/hotel.add-pet'
import { Route as HotelBookingIdRouteImport } from './routes/hotel.$bookingId'
import { Route as ClinicReportsRouteImport } from './routes/clinic.reports'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as ApiSpeciesRouteImport } from './routes/api/species'
import { Route as ApiPetsRouteImport } from './routes/api/pets'
import { Route as ApiHotelBookingsRouteImport } from './routes/api/hotel-bookings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as HotelNewIndexRouteImport } from './routes/hotel/new/index'
import { Route as VetVisitsVisitIdRouteImport } from './routes/vet.visits.$visitId'
import { Route as VetHotelBookingIdRouteImport } from './routes/vet.hotel.$bookingId'
import { Route as VetDailyReportsReportIdRouteImport } from './routes/vet.daily-reports.$reportId'
import { Route as ShareVetTokenRouteImport } from './routes/share.vet.$token'
import { Route as ShareHotelTokenRouteImport } from './routes/share.hotel.$token'
import { Route as PetsPetIdEditRouteImport } from './routes/pets/$petId.edit'
import { Route as HotelNewPetIdRouteImport } from './routes/hotel/new/$petId'
import { Route as ApiVisitsVisitIdRouteImport } from './routes/api/visits.$visitId'
import { Route as ApiUsersRegisterForVetRouteImport } from './routes/api/users.register-for-vet'
import { Route as ApiUsersRegisterForHotelRouteImport } from './routes/api/users.register-for-hotel'
import { Route as ApiUsersPhoneCheckRouteImport } from './routes/api/users.phone-check'
import { Route as ApiUsersMeRouteImport } from './routes/api/users.me'
import { Route as ApiSearchPetRouteImport } from './routes/api/search.pet'
import { Route as ApiSearchOwnerRouteImport } from './routes/api/search.owner'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products.$productId'
import { Route as ApiPetsPetIdRouteImport } from './routes/api/pets.$petId'
import { Route as ApiHotelStandaloneRouteImport } from './routes/api/hotel.standalone'
import { Route as ApiHotelBookingIdRouteImport } from './routes/api/hotel.$bookingId'
import { Route as ApiHotelBookingsBookingIdRouteImport } from './routes/api/hotel-bookings.$bookingId'
import { Route as ApiDailyReportsReportIdRouteImport } from './routes/api/daily-reports.$reportId'
import { Route as ApiClinicMineRouteImport } from './routes/api/clinic.mine'
import { Route as ApiClinicClinicIdRouteImport } from './routes/api/clinic.$clinicId'
import { Route as VetVisitsNewPetIdRouteImport } from './routes/vet.visits.new.$petId'
import { Route as VetHotelNewPetIdRouteImport } from './routes/vet.hotel.new.$petId'
import { Route as ApiVisitsVisitIdShareRouteImport } from './routes/api/visits.$visitId.share'
import { Route as ApiVisitsVisitIdDailyReportsRouteImport } from './routes/api/visits.$visitId.daily-reports'
import { Route as ApiUsersMeRegisterPetOwnerRouteImport } from './routes/api/users.me.register-pet-owner'
import { Route as ApiShareVetTokenRouteImport } from './routes/api/share.vet.$token'
import { Route as ApiShareHotelTokenRouteImport } from './routes/api/share.hotel.$token'
import { Route as ApiPetsPetIdVaccinationsRouteImport } from './routes/api/pets.$petId.vaccinations'
import { Route as ApiPetsPetIdHealthEventsRouteImport } from './routes/api/pets.$petId.health-events'
import { Route as ApiHotelBookingIdShareRouteImport } from './routes/api/hotel.$bookingId.share'
import { Route as ApiHotelBookingIdLogsRouteImport } from './routes/api/hotel.$bookingId.logs'
import { Route as ApiHotelBookingsBookingIdDailyLogsRouteImport } from './routes/api/hotel-bookings.$bookingId.daily-logs'
import { Route as ApiClinicClinicIdStaffRouteImport } from './routes/api/clinic.$clinicId.staff'
import { Route as ApiClinicClinicIdProductsRouteImport } from './routes/api/clinic.$clinicId.products'
import { Route as ApiPetsPetIdVaccinationsVaccinationIdRouteImport } from './routes/api/pets.$petId.vaccinations.$vaccinationId'
import { Route as ApiPetsPetIdHealthEventsEventIdRouteImport } from './routes/api/pets.$petId.health-events.$eventId'
import { Route as ApiHotelClinicClinicIdBookingsRouteImport } from './routes/api/hotel.clinic.$clinicId.bookings'
import { Route as ApiHotelHotelIdReportsSummaryRouteImport } from './routes/api/hotel.$hotelId.reports.summary'
import { Route as ApiHotelBookingIdLogsLogIdRouteImport } from './routes/api/hotel.$bookingId.logs.$logId'
import { Route as ApiHotelBookingsBookingIdDailyLogsLogIdRouteImport } from './routes/api/hotel-bookings.$bookingId.daily-logs.$logId'
import { Route as ApiClinicClinicIdStaffStaffIdRouteImport } from './routes/api/clinic.$clinicId.staff.$staffId'
import { Route as ApiClinicClinicIdReportsSummaryRouteImport } from './routes/api/clinic.$clinicId.reports.summary'
import { Route as ApiClinicClinicIdReportsStatsRouteImport } from './routes/api/clinic.$clinicId.reports.stats'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetIndexRoute = VetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/clinic/',
  path: '/clinic/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetSearchRoute = VetSearchRouteImport.update({
  id: '/vet/search',
  path: '/vet/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VetReportsRoute = VetReportsRouteImport.update({
  id: '/vet/reports',
  path: '/vet/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VetHotelRoute = VetHotelRouteImport.update({
  id: '/vet/hotel',
  path: '/vet/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const VetAddPetRoute = VetAddPetRouteImport.update({
  id: '/vet/add-pet',
  path: '/vet/add-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelSearchRoute = HotelSearchRouteImport.update({
  id: '/hotel/search',
  path: '/hotel/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelReportsRoute = HotelReportsRouteImport.update({
  id: '/hotel/reports',
  path: '/hotel/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelHistoryRoute = HotelHistoryRouteImport.update({
  id: '/hotel/history',
  path: '/hotel/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelGuestsRoute = HotelGuestsRouteImport.update({
  id: '/hotel/guests',
  path: '/hotel/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAddPetRoute = HotelAddPetRouteImport.update({
  id: '/hotel/add-pet',
  path: '/hotel/add-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingIdRoute = HotelBookingIdRouteImport.update({
  id: '/hotel/$bookingId',
  path: '/hotel/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicReportsRoute = ClinicReportsRouteImport.update({
  id: '/clinic/reports',
  path: '/clinic/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeciesRoute = ApiSpeciesRouteImport.update({
  id: '/api/species',
  path: '/api/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetsRoute = ApiPetsRouteImport.update({
  id: '/api/pets',
  path: '/api/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelBookingsRoute = ApiHotelBookingsRouteImport.update({
  id: '/api/hotel-bookings',
  path: '/api/hotel-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNewIndexRoute = HotelNewIndexRouteImport.update({
  id: '/hotel/new/',
  path: '/hotel/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetVisitsVisitIdRoute = VetVisitsVisitIdRouteImport.update({
  id: '/vet/visits/$visitId',
  path: '/vet/visits/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const VetHotelBookingIdRoute = VetHotelBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => VetHotelRoute,
} as any)
const VetDailyReportsReportIdRoute = VetDailyReportsReportIdRouteImport.update({
  id: '/vet/daily-reports/$reportId',
  path: '/vet/daily-reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareVetTokenRoute = ShareVetTokenRouteImport.update({
  id: '/share/vet/$token',
  path: '/share/vet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareHotelTokenRoute = ShareHotelTokenRouteImport.update({
  id: '/share/hotel/$token',
  path: '/share/hotel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdEditRoute = PetsPetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const HotelNewPetIdRoute = HotelNewPetIdRouteImport.update({
  id: '/hotel/new/$petId',
  path: '/hotel/new/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitsVisitIdRoute = ApiVisitsVisitIdRouteImport.update({
  id: '/$visitId',
  path: '/$visitId',
  getParentRoute: () => ApiVisitsRoute,
} as any)
const ApiUsersRegisterForVetRoute = ApiUsersRegisterForVetRouteImport.update({
  id: '/api/users/register-for-vet',
  path: '/api/users/register-for-vet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRegisterForHotelRoute =
  ApiUsersRegisterForHotelRouteImport.update({
    id: '/api/users/register-for-hotel',
    path: '/api/users/register-for-hotel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersPhoneCheckRoute = ApiUsersPhoneCheckRouteImport.update({
  id: '/api/users/phone-check',
  path: '/api/users/phone-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchPetRoute = ApiSearchPetRouteImport.update({
  id: '/api/search/pet',
  path: '/api/search/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchOwnerRoute = ApiSearchOwnerRouteImport.update({
  id: '/api/search/owner',
  path: '/api/search/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/api/products/$productId',
  path: '/api/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetsPetIdRoute = ApiPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => ApiPetsRoute,
} as any)
const ApiHotelStandaloneRoute = ApiHotelStandaloneRouteImport.update({
  id: '/api/hotel/standalone',
  path: '/api/hotel/standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelBookingIdRoute = ApiHotelBookingIdRouteImport.update({
  id: '/api/hotel/$bookingId',
  path: '/api/hotel/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelBookingsBookingIdRoute =
  ApiHotelBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => ApiHotelBookingsRoute,
  } as any)
const ApiDailyReportsReportIdRoute = ApiDailyReportsReportIdRouteImport.update({
  id: '/api/daily-reports/$reportId',
  path: '/api/daily-reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClinicMineRoute = ApiClinicMineRouteImport.update({
  id: '/api/clinic/mine',
  path: '/api/clinic/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClinicClinicIdRoute = ApiClinicClinicIdRouteImport.update({
  id: '/api/clinic/$clinicId',
  path: '/api/clinic/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)
const VetVisitsNewPetIdRoute = VetVisitsNewPetIdRouteImport.update({
  id: '/vet/visits/new/$petId',
  path: '/vet/visits/new/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const VetHotelNewPetIdRoute = VetHotelNewPetIdRouteImport.update({
  id: '/new/$petId',
  path: '/new/$petId',
  getParentRoute: () => VetHotelRoute,
} as any)
const ApiVisitsVisitIdShareRoute = ApiVisitsVisitIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ApiVisitsVisitIdRoute,
} as any)
const ApiVisitsVisitIdDailyReportsRoute =
  ApiVisitsVisitIdDailyReportsRouteImport.update({
    id: '/daily-reports',
    path: '/daily-reports',
    getParentRoute: () => ApiVisitsVisitIdRoute,
  } as any)
const ApiUsersMeRegisterPetOwnerRoute =
  ApiUsersMeRegisterPetOwnerRouteImport.update({
    id: '/register-pet-owner',
    path: '/register-pet-owner',
    getParentRoute: () => ApiUsersMeRoute,
  } as any)
const ApiShareVetTokenRoute = ApiShareVetTokenRouteImport.update({
  id: '/api/share/vet/$token',
  path: '/api/share/vet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareHotelTokenRoute = ApiShareHotelTokenRouteImport.update({
  id: '/api/share/hotel/$token',
  path: '/api/share/hotel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetsPetIdVaccinationsRoute =
  ApiPetsPetIdVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => ApiPetsPetIdRoute,
  } as any)
const ApiPetsPetIdHealthEventsRoute =
  ApiPetsPetIdHealthEventsRouteImport.update({
    id: '/health-events',
    path: '/health-events',
    getParentRoute: () => ApiPetsPetIdRoute,
  } as any)
const ApiHotelBookingIdShareRoute = ApiHotelBookingIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ApiHotelBookingIdRoute,
} as any)
const ApiHotelBookingIdLogsRoute = ApiHotelBookingIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiHotelBookingIdRoute,
} as any)
const ApiHotelBookingsBookingIdDailyLogsRoute =
  ApiHotelBookingsBookingIdDailyLogsRouteImport.update({
    id: '/daily-logs',
    path: '/daily-logs',
    getParentRoute: () => ApiHotelBookingsBookingIdRoute,
  } as any)
const ApiClinicClinicIdStaffRoute = ApiClinicClinicIdStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ApiClinicClinicIdRoute,
} as any)
const ApiClinicClinicIdProductsRoute =
  ApiClinicClinicIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ApiClinicClinicIdRoute,
  } as any)
const ApiPetsPetIdVaccinationsVaccinationIdRoute =
  ApiPetsPetIdVaccinationsVaccinationIdRouteImport.update({
    id: '/$vaccinationId',
    path: '/$vaccinationId',
    getParentRoute: () => ApiPetsPetIdVaccinationsRoute,
  } as any)
const ApiPetsPetIdHealthEventsEventIdRoute =
  ApiPetsPetIdHealthEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => ApiPetsPetIdHealthEventsRoute,
  } as any)
const ApiHotelClinicClinicIdBookingsRoute =
  ApiHotelClinicClinicIdBookingsRouteImport.update({
    id: '/api/hotel/clinic/$clinicId/bookings',
    path: '/api/hotel/clinic/$clinicId/bookings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHotelHotelIdReportsSummaryRoute =
  ApiHotelHotelIdReportsSummaryRouteImport.update({
    id: '/api/hotel/$hotelId/reports/summary',
    path: '/api/hotel/$hotelId/reports/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHotelBookingIdLogsLogIdRoute =
  ApiHotelBookingIdLogsLogIdRouteImport.update({
    id: '/$logId',
    path: '/$logId',
    getParentRoute: () => ApiHotelBookingIdLogsRoute,
  } as any)
const ApiHotelBookingsBookingIdDailyLogsLogIdRoute =
  ApiHotelBookingsBookingIdDailyLogsLogIdRouteImport.update({
    id: '/$logId',
    path: '/$logId',
    getParentRoute: () => ApiHotelBookingsBookingIdDailyLogsRoute,
  } as any)
const ApiClinicClinicIdStaffStaffIdRoute =
  ApiClinicClinicIdStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => ApiClinicClinicIdStaffRoute,
  } as any)
const ApiClinicClinicIdReportsSummaryRoute =
  ApiClinicClinicIdReportsSummaryRouteImport.update({
    id: '/reports/summary',
    path: '/reports/summary',
    getParentRoute: () => ApiClinicClinicIdRoute,
  } as any)
const ApiClinicClinicIdReportsStatsRoute =
  ApiClinicClinicIdReportsStatsRouteImport.update({
    id: '/reports/stats',
    path: '/reports/stats',
    getParentRoute: () => ApiClinicClinicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hotel-bookings': typeof ApiHotelBookingsRouteWithChildren
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRouteWithChildren
  '/clinic/reports': typeof ClinicReportsRoute
  '/hotel/$bookingId': typeof HotelBookingIdRoute
  '/hotel/add-pet': typeof HotelAddPetRoute
  '/hotel/guests': typeof HotelGuestsRoute
  '/hotel/history': typeof HotelHistoryRoute
  '/hotel/reports': typeof HotelReportsRoute
  '/hotel/search': typeof HotelSearchRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/pets/new': typeof PetsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/vet/add-pet': typeof VetAddPetRoute
  '/vet/hotel': typeof VetHotelRouteWithChildren
  '/vet/reports': typeof VetReportsRoute
  '/vet/search': typeof VetSearchRoute
  '/clinic/': typeof ClinicIndexRoute
  '/hotel/': typeof HotelIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/vet/': typeof VetIndexRoute
  '/api/clinic/$clinicId': typeof ApiClinicClinicIdRouteWithChildren
  '/api/clinic/mine': typeof ApiClinicMineRoute
  '/api/daily-reports/$reportId': typeof ApiDailyReportsReportIdRoute
  '/api/hotel-bookings/$bookingId': typeof ApiHotelBookingsBookingIdRouteWithChildren
  '/api/hotel/$bookingId': typeof ApiHotelBookingIdRouteWithChildren
  '/api/hotel/standalone': typeof ApiHotelStandaloneRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/search/owner': typeof ApiSearchOwnerRoute
  '/api/search/pet': typeof ApiSearchPetRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/phone-check': typeof ApiUsersPhoneCheckRoute
  '/api/users/register-for-hotel': typeof ApiUsersRegisterForHotelRoute
  '/api/users/register-for-vet': typeof ApiUsersRegisterForVetRoute
  '/api/visits/$visitId': typeof ApiVisitsVisitIdRouteWithChildren
  '/hotel/new/$petId': typeof HotelNewPetIdRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/share/hotel/$token': typeof ShareHotelTokenRoute
  '/share/vet/$token': typeof ShareVetTokenRoute
  '/vet/daily-reports/$reportId': typeof VetDailyReportsReportIdRoute
  '/vet/hotel/$bookingId': typeof VetHotelBookingIdRoute
  '/vet/visits/$visitId': typeof VetVisitsVisitIdRoute
  '/hotel/new/': typeof HotelNewIndexRoute
  '/api/clinic/$clinicId/products': typeof ApiClinicClinicIdProductsRoute
  '/api/clinic/$clinicId/staff': typeof ApiClinicClinicIdStaffRouteWithChildren
  '/api/hotel-bookings/$bookingId/daily-logs': typeof ApiHotelBookingsBookingIdDailyLogsRouteWithChildren
  '/api/hotel/$bookingId/logs': typeof ApiHotelBookingIdLogsRouteWithChildren
  '/api/hotel/$bookingId/share': typeof ApiHotelBookingIdShareRoute
  '/api/pets/$petId/health-events': typeof ApiPetsPetIdHealthEventsRouteWithChildren
  '/api/pets/$petId/vaccinations': typeof ApiPetsPetIdVaccinationsRouteWithChildren
  '/api/share/hotel/$token': typeof ApiShareHotelTokenRoute
  '/api/share/vet/$token': typeof ApiShareVetTokenRoute
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
  '/api/visits/$visitId/daily-reports': typeof ApiVisitsVisitIdDailyReportsRoute
  '/api/visits/$visitId/share': typeof ApiVisitsVisitIdShareRoute
  '/vet/hotel/new/$petId': typeof VetHotelNewPetIdRoute
  '/vet/visits/new/$petId': typeof VetVisitsNewPetIdRoute
  '/api/clinic/$clinicId/reports/stats': typeof ApiClinicClinicIdReportsStatsRoute
  '/api/clinic/$clinicId/reports/summary': typeof ApiClinicClinicIdReportsSummaryRoute
  '/api/clinic/$clinicId/staff/$staffId': typeof ApiClinicClinicIdStaffStaffIdRoute
  '/api/hotel-bookings/$bookingId/daily-logs/$logId': typeof ApiHotelBookingsBookingIdDailyLogsLogIdRoute
  '/api/hotel/$bookingId/logs/$logId': typeof ApiHotelBookingIdLogsLogIdRoute
  '/api/hotel/$hotelId/reports/summary': typeof ApiHotelHotelIdReportsSummaryRoute
  '/api/hotel/clinic/$clinicId/bookings': typeof ApiHotelClinicClinicIdBookingsRoute
  '/api/pets/$petId/health-events/$eventId': typeof ApiPetsPetIdHealthEventsEventIdRoute
  '/api/pets/$petId/vaccinations/$vaccinationId': typeof ApiPetsPetIdVaccinationsVaccinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hotel-bookings': typeof ApiHotelBookingsRouteWithChildren
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRouteWithChildren
  '/clinic/reports': typeof ClinicReportsRoute
  '/hotel/$bookingId': typeof HotelBookingIdRoute
  '/hotel/add-pet': typeof HotelAddPetRoute
  '/hotel/guests': typeof HotelGuestsRoute
  '/hotel/history': typeof HotelHistoryRoute
  '/hotel/reports': typeof HotelReportsRoute
  '/hotel/search': typeof HotelSearchRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/pets/new': typeof PetsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/vet/add-pet': typeof VetAddPetRoute
  '/vet/hotel': typeof VetHotelRouteWithChildren
  '/vet/reports': typeof VetReportsRoute
  '/vet/search': typeof VetSearchRoute
  '/clinic': typeof ClinicIndexRoute
  '/hotel': typeof HotelIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/pets': typeof PetsIndexRoute
  '/vet': typeof VetIndexRoute
  '/api/clinic/$clinicId': typeof ApiClinicClinicIdRouteWithChildren
  '/api/clinic/mine': typeof ApiClinicMineRoute
  '/api/daily-reports/$reportId': typeof ApiDailyReportsReportIdRoute
  '/api/hotel-bookings/$bookingId': typeof ApiHotelBookingsBookingIdRouteWithChildren
  '/api/hotel/$bookingId': typeof ApiHotelBookingIdRouteWithChildren
  '/api/hotel/standalone': typeof ApiHotelStandaloneRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/search/owner': typeof ApiSearchOwnerRoute
  '/api/search/pet': typeof ApiSearchPetRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/phone-check': typeof ApiUsersPhoneCheckRoute
  '/api/users/register-for-hotel': typeof ApiUsersRegisterForHotelRoute
  '/api/users/register-for-vet': typeof ApiUsersRegisterForVetRoute
  '/api/visits/$visitId': typeof ApiVisitsVisitIdRouteWithChildren
  '/hotel/new/$petId': typeof HotelNewPetIdRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/share/hotel/$token': typeof ShareHotelTokenRoute
  '/share/vet/$token': typeof ShareVetTokenRoute
  '/vet/daily-reports/$reportId': typeof VetDailyReportsReportIdRoute
  '/vet/hotel/$bookingId': typeof VetHotelBookingIdRoute
  '/vet/visits/$visitId': typeof VetVisitsVisitIdRoute
  '/hotel/new': typeof HotelNewIndexRoute
  '/api/clinic/$clinicId/products': typeof ApiClinicClinicIdProductsRoute
  '/api/clinic/$clinicId/staff': typeof ApiClinicClinicIdStaffRouteWithChildren
  '/api/hotel-bookings/$bookingId/daily-logs': typeof ApiHotelBookingsBookingIdDailyLogsRouteWithChildren
  '/api/hotel/$bookingId/logs': typeof ApiHotelBookingIdLogsRouteWithChildren
  '/api/hotel/$bookingId/share': typeof ApiHotelBookingIdShareRoute
  '/api/pets/$petId/health-events': typeof ApiPetsPetIdHealthEventsRouteWithChildren
  '/api/pets/$petId/vaccinations': typeof ApiPetsPetIdVaccinationsRouteWithChildren
  '/api/share/hotel/$token': typeof ApiShareHotelTokenRoute
  '/api/share/vet/$token': typeof ApiShareVetTokenRoute
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
  '/api/visits/$visitId/daily-reports': typeof ApiVisitsVisitIdDailyReportsRoute
  '/api/visits/$visitId/share': typeof ApiVisitsVisitIdShareRoute
  '/vet/hotel/new/$petId': typeof VetHotelNewPetIdRoute
  '/vet/visits/new/$petId': typeof VetVisitsNewPetIdRoute
  '/api/clinic/$clinicId/reports/stats': typeof ApiClinicClinicIdReportsStatsRoute
  '/api/clinic/$clinicId/reports/summary': typeof ApiClinicClinicIdReportsSummaryRoute
  '/api/clinic/$clinicId/staff/$staffId': typeof ApiClinicClinicIdStaffStaffIdRoute
  '/api/hotel-bookings/$bookingId/daily-logs/$logId': typeof ApiHotelBookingsBookingIdDailyLogsLogIdRoute
  '/api/hotel/$bookingId/logs/$logId': typeof ApiHotelBookingIdLogsLogIdRoute
  '/api/hotel/$hotelId/reports/summary': typeof ApiHotelHotelIdReportsSummaryRoute
  '/api/hotel/clinic/$clinicId/bookings': typeof ApiHotelClinicClinicIdBookingsRoute
  '/api/pets/$petId/health-events/$eventId': typeof ApiPetsPetIdHealthEventsEventIdRoute
  '/api/pets/$petId/vaccinations/$vaccinationId': typeof ApiPetsPetIdVaccinationsVaccinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hotel-bookings': typeof ApiHotelBookingsRouteWithChildren
  '/api/pets': typeof ApiPetsRouteWithChildren
  '/api/species': typeof ApiSpeciesRoute
  '/api/visits': typeof ApiVisitsRouteWithChildren
  '/clinic/reports': typeof ClinicReportsRoute
  '/hotel/$bookingId': typeof HotelBookingIdRoute
  '/hotel/add-pet': typeof HotelAddPetRoute
  '/hotel/guests': typeof HotelGuestsRoute
  '/hotel/history': typeof HotelHistoryRoute
  '/hotel/reports': typeof HotelReportsRoute
  '/hotel/search': typeof HotelSearchRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/pets/new': typeof PetsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/vet/add-pet': typeof VetAddPetRoute
  '/vet/hotel': typeof VetHotelRouteWithChildren
  '/vet/reports': typeof VetReportsRoute
  '/vet/search': typeof VetSearchRoute
  '/clinic/': typeof ClinicIndexRoute
  '/hotel/': typeof HotelIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/vet/': typeof VetIndexRoute
  '/api/clinic/$clinicId': typeof ApiClinicClinicIdRouteWithChildren
  '/api/clinic/mine': typeof ApiClinicMineRoute
  '/api/daily-reports/$reportId': typeof ApiDailyReportsReportIdRoute
  '/api/hotel-bookings/$bookingId': typeof ApiHotelBookingsBookingIdRouteWithChildren
  '/api/hotel/$bookingId': typeof ApiHotelBookingIdRouteWithChildren
  '/api/hotel/standalone': typeof ApiHotelStandaloneRoute
  '/api/pets/$petId': typeof ApiPetsPetIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/search/owner': typeof ApiSearchOwnerRoute
  '/api/search/pet': typeof ApiSearchPetRoute
  '/api/users/me': typeof ApiUsersMeRouteWithChildren
  '/api/users/phone-check': typeof ApiUsersPhoneCheckRoute
  '/api/users/register-for-hotel': typeof ApiUsersRegisterForHotelRoute
  '/api/users/register-for-vet': typeof ApiUsersRegisterForVetRoute
  '/api/visits/$visitId': typeof ApiVisitsVisitIdRouteWithChildren
  '/hotel/new/$petId': typeof HotelNewPetIdRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/share/hotel/$token': typeof ShareHotelTokenRoute
  '/share/vet/$token': typeof ShareVetTokenRoute
  '/vet/daily-reports/$reportId': typeof VetDailyReportsReportIdRoute
  '/vet/hotel/$bookingId': typeof VetHotelBookingIdRoute
  '/vet/visits/$visitId': typeof VetVisitsVisitIdRoute
  '/hotel/new/': typeof HotelNewIndexRoute
  '/api/clinic/$clinicId/products': typeof ApiClinicClinicIdProductsRoute
  '/api/clinic/$clinicId/staff': typeof ApiClinicClinicIdStaffRouteWithChildren
  '/api/hotel-bookings/$bookingId/daily-logs': typeof ApiHotelBookingsBookingIdDailyLogsRouteWithChildren
  '/api/hotel/$bookingId/logs': typeof ApiHotelBookingIdLogsRouteWithChildren
  '/api/hotel/$bookingId/share': typeof ApiHotelBookingIdShareRoute
  '/api/pets/$petId/health-events': typeof ApiPetsPetIdHealthEventsRouteWithChildren
  '/api/pets/$petId/vaccinations': typeof ApiPetsPetIdVaccinationsRouteWithChildren
  '/api/share/hotel/$token': typeof ApiShareHotelTokenRoute
  '/api/share/vet/$token': typeof ApiShareVetTokenRoute
  '/api/users/me/register-pet-owner': typeof ApiUsersMeRegisterPetOwnerRoute
  '/api/visits/$visitId/daily-reports': typeof ApiVisitsVisitIdDailyReportsRoute
  '/api/visits/$visitId/share': typeof ApiVisitsVisitIdShareRoute
  '/vet/hotel/new/$petId': typeof VetHotelNewPetIdRoute
  '/vet/visits/new/$petId': typeof VetVisitsNewPetIdRoute
  '/api/clinic/$clinicId/reports/stats': typeof ApiClinicClinicIdReportsStatsRoute
  '/api/clinic/$clinicId/reports/summary': typeof ApiClinicClinicIdReportsSummaryRoute
  '/api/clinic/$clinicId/staff/$staffId': typeof ApiClinicClinicIdStaffStaffIdRoute
  '/api/hotel-bookings/$bookingId/daily-logs/$logId': typeof ApiHotelBookingsBookingIdDailyLogsLogIdRoute
  '/api/hotel/$bookingId/logs/$logId': typeof ApiHotelBookingIdLogsLogIdRoute
  '/api/hotel/$hotelId/reports/summary': typeof ApiHotelHotelIdReportsSummaryRoute
  '/api/hotel/clinic/$clinicId/bookings': typeof ApiHotelClinicClinicIdBookingsRoute
  '/api/pets/$petId/health-events/$eventId': typeof ApiPetsPetIdHealthEventsEventIdRoute
  '/api/pets/$petId/vaccinations/$vaccinationId': typeof ApiPetsPetIdVaccinationsVaccinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/api/hotel-bookings'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/clinic/reports'
    | '/hotel/$bookingId'
    | '/hotel/add-pet'
    | '/hotel/guests'
    | '/hotel/history'
    | '/hotel/reports'
    | '/hotel/search'
    | '/pets/$petId'
    | '/pets/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/vet/add-pet'
    | '/vet/hotel'
    | '/vet/reports'
    | '/vet/search'
    | '/clinic/'
    | '/hotel/'
    | '/onboarding/'
    | '/pets/'
    | '/vet/'
    | '/api/clinic/$clinicId'
    | '/api/clinic/mine'
    | '/api/daily-reports/$reportId'
    | '/api/hotel-bookings/$bookingId'
    | '/api/hotel/$bookingId'
    | '/api/hotel/standalone'
    | '/api/pets/$petId'
    | '/api/products/$productId'
    | '/api/search/owner'
    | '/api/search/pet'
    | '/api/users/me'
    | '/api/users/phone-check'
    | '/api/users/register-for-hotel'
    | '/api/users/register-for-vet'
    | '/api/visits/$visitId'
    | '/hotel/new/$petId'
    | '/pets/$petId/edit'
    | '/share/hotel/$token'
    | '/share/vet/$token'
    | '/vet/daily-reports/$reportId'
    | '/vet/hotel/$bookingId'
    | '/vet/visits/$visitId'
    | '/hotel/new/'
    | '/api/clinic/$clinicId/products'
    | '/api/clinic/$clinicId/staff'
    | '/api/hotel-bookings/$bookingId/daily-logs'
    | '/api/hotel/$bookingId/logs'
    | '/api/hotel/$bookingId/share'
    | '/api/pets/$petId/health-events'
    | '/api/pets/$petId/vaccinations'
    | '/api/share/hotel/$token'
    | '/api/share/vet/$token'
    | '/api/users/me/register-pet-owner'
    | '/api/visits/$visitId/daily-reports'
    | '/api/visits/$visitId/share'
    | '/vet/hotel/new/$petId'
    | '/vet/visits/new/$petId'
    | '/api/clinic/$clinicId/reports/stats'
    | '/api/clinic/$clinicId/reports/summary'
    | '/api/clinic/$clinicId/staff/$staffId'
    | '/api/hotel-bookings/$bookingId/daily-logs/$logId'
    | '/api/hotel/$bookingId/logs/$logId'
    | '/api/hotel/$hotelId/reports/summary'
    | '/api/hotel/clinic/$clinicId/bookings'
    | '/api/pets/$petId/health-events/$eventId'
    | '/api/pets/$petId/vaccinations/$vaccinationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/api/hotel-bookings'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/clinic/reports'
    | '/hotel/$bookingId'
    | '/hotel/add-pet'
    | '/hotel/guests'
    | '/hotel/history'
    | '/hotel/reports'
    | '/hotel/search'
    | '/pets/$petId'
    | '/pets/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/vet/add-pet'
    | '/vet/hotel'
    | '/vet/reports'
    | '/vet/search'
    | '/clinic'
    | '/hotel'
    | '/onboarding'
    | '/pets'
    | '/vet'
    | '/api/clinic/$clinicId'
    | '/api/clinic/mine'
    | '/api/daily-reports/$reportId'
    | '/api/hotel-bookings/$bookingId'
    | '/api/hotel/$bookingId'
    | '/api/hotel/standalone'
    | '/api/pets/$petId'
    | '/api/products/$productId'
    | '/api/search/owner'
    | '/api/search/pet'
    | '/api/users/me'
    | '/api/users/phone-check'
    | '/api/users/register-for-hotel'
    | '/api/users/register-for-vet'
    | '/api/visits/$visitId'
    | '/hotel/new/$petId'
    | '/pets/$petId/edit'
    | '/share/hotel/$token'
    | '/share/vet/$token'
    | '/vet/daily-reports/$reportId'
    | '/vet/hotel/$bookingId'
    | '/vet/visits/$visitId'
    | '/hotel/new'
    | '/api/clinic/$clinicId/products'
    | '/api/clinic/$clinicId/staff'
    | '/api/hotel-bookings/$bookingId/daily-logs'
    | '/api/hotel/$bookingId/logs'
    | '/api/hotel/$bookingId/share'
    | '/api/pets/$petId/health-events'
    | '/api/pets/$petId/vaccinations'
    | '/api/share/hotel/$token'
    | '/api/share/vet/$token'
    | '/api/users/me/register-pet-owner'
    | '/api/visits/$visitId/daily-reports'
    | '/api/visits/$visitId/share'
    | '/vet/hotel/new/$petId'
    | '/vet/visits/new/$petId'
    | '/api/clinic/$clinicId/reports/stats'
    | '/api/clinic/$clinicId/reports/summary'
    | '/api/clinic/$clinicId/staff/$staffId'
    | '/api/hotel-bookings/$bookingId/daily-logs/$logId'
    | '/api/hotel/$bookingId/logs/$logId'
    | '/api/hotel/$hotelId/reports/summary'
    | '/api/hotel/clinic/$clinicId/bookings'
    | '/api/pets/$petId/health-events/$eventId'
    | '/api/pets/$petId/vaccinations/$vaccinationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/api/hotel-bookings'
    | '/api/pets'
    | '/api/species'
    | '/api/visits'
    | '/clinic/reports'
    | '/hotel/$bookingId'
    | '/hotel/add-pet'
    | '/hotel/guests'
    | '/hotel/history'
    | '/hotel/reports'
    | '/hotel/search'
    | '/pets/$petId'
    | '/pets/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/vet/add-pet'
    | '/vet/hotel'
    | '/vet/reports'
    | '/vet/search'
    | '/clinic/'
    | '/hotel/'
    | '/onboarding/'
    | '/pets/'
    | '/vet/'
    | '/api/clinic/$clinicId'
    | '/api/clinic/mine'
    | '/api/daily-reports/$reportId'
    | '/api/hotel-bookings/$bookingId'
    | '/api/hotel/$bookingId'
    | '/api/hotel/standalone'
    | '/api/pets/$petId'
    | '/api/products/$productId'
    | '/api/search/owner'
    | '/api/search/pet'
    | '/api/users/me'
    | '/api/users/phone-check'
    | '/api/users/register-for-hotel'
    | '/api/users/register-for-vet'
    | '/api/visits/$visitId'
    | '/hotel/new/$petId'
    | '/pets/$petId/edit'
    | '/share/hotel/$token'
    | '/share/vet/$token'
    | '/vet/daily-reports/$reportId'
    | '/vet/hotel/$bookingId'
    | '/vet/visits/$visitId'
    | '/hotel/new/'
    | '/api/clinic/$clinicId/products'
    | '/api/clinic/$clinicId/staff'
    | '/api/hotel-bookings/$bookingId/daily-logs'
    | '/api/hotel/$bookingId/logs'
    | '/api/hotel/$bookingId/share'
    | '/api/pets/$petId/health-events'
    | '/api/pets/$petId/vaccinations'
    | '/api/share/hotel/$token'
    | '/api/share/vet/$token'
    | '/api/users/me/register-pet-owner'
    | '/api/visits/$visitId/daily-reports'
    | '/api/visits/$visitId/share'
    | '/vet/hotel/new/$petId'
    | '/vet/visits/new/$petId'
    | '/api/clinic/$clinicId/reports/stats'
    | '/api/clinic/$clinicId/reports/summary'
    | '/api/clinic/$clinicId/staff/$staffId'
    | '/api/hotel-bookings/$bookingId/daily-logs/$logId'
    | '/api/hotel/$bookingId/logs/$logId'
    | '/api/hotel/$hotelId/reports/summary'
    | '/api/hotel/clinic/$clinicId/bookings'
    | '/api/pets/$petId/health-events/$eventId'
    | '/api/pets/$petId/vaccinations/$vaccinationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHotelBookingsRoute: typeof ApiHotelBookingsRouteWithChildren
  ApiPetsRoute: typeof ApiPetsRouteWithChildren
  ApiSpeciesRoute: typeof ApiSpeciesRoute
  ApiVisitsRoute: typeof ApiVisitsRouteWithChildren
  ClinicReportsRoute: typeof ClinicReportsRoute
  HotelBookingIdRoute: typeof HotelBookingIdRoute
  HotelAddPetRoute: typeof HotelAddPetRoute
  HotelGuestsRoute: typeof HotelGuestsRoute
  HotelHistoryRoute: typeof HotelHistoryRoute
  HotelReportsRoute: typeof HotelReportsRoute
  HotelSearchRoute: typeof HotelSearchRoute
  PetsPetIdRoute: typeof PetsPetIdRouteWithChildren
  PetsNewRoute: typeof PetsNewRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  VetAddPetRoute: typeof VetAddPetRoute
  VetHotelRoute: typeof VetHotelRouteWithChildren
  VetReportsRoute: typeof VetReportsRoute
  VetSearchRoute: typeof VetSearchRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
  HotelIndexRoute: typeof HotelIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PetsIndexRoute: typeof PetsIndexRoute
  VetIndexRoute: typeof VetIndexRoute
  ApiClinicClinicIdRoute: typeof ApiClinicClinicIdRouteWithChildren
  ApiClinicMineRoute: typeof ApiClinicMineRoute
  ApiDailyReportsReportIdRoute: typeof ApiDailyReportsReportIdRoute
  ApiHotelBookingIdRoute: typeof ApiHotelBookingIdRouteWithChildren
  ApiHotelStandaloneRoute: typeof ApiHotelStandaloneRoute
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
  ApiSearchOwnerRoute: typeof ApiSearchOwnerRoute
  ApiSearchPetRoute: typeof ApiSearchPetRoute
  ApiUsersMeRoute: typeof ApiUsersMeRouteWithChildren
  ApiUsersPhoneCheckRoute: typeof ApiUsersPhoneCheckRoute
  ApiUsersRegisterForHotelRoute: typeof ApiUsersRegisterForHotelRoute
  ApiUsersRegisterForVetRoute: typeof ApiUsersRegisterForVetRoute
  HotelNewPetIdRoute: typeof HotelNewPetIdRoute
  ShareHotelTokenRoute: typeof ShareHotelTokenRoute
  ShareVetTokenRoute: typeof ShareVetTokenRoute
  VetDailyReportsReportIdRoute: typeof VetDailyReportsReportIdRoute
  VetVisitsVisitIdRoute: typeof VetVisitsVisitIdRoute
  HotelNewIndexRoute: typeof HotelNewIndexRoute
  ApiShareHotelTokenRoute: typeof ApiShareHotelTokenRoute
  ApiShareVetTokenRoute: typeof ApiShareVetTokenRoute
  VetVisitsNewPetIdRoute: typeof VetVisitsNewPetIdRoute
  ApiHotelHotelIdReportsSummaryRoute: typeof ApiHotelHotelIdReportsSummaryRoute
  ApiHotelClinicClinicIdBookingsRoute: typeof ApiHotelClinicClinicIdBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/': {
      id: '/vet/'
      path: '/vet'
      fullPath: '/vet/'
      preLoaderRoute: typeof VetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/hotel'
      fullPath: '/hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/clinic'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/search': {
      id: '/vet/search'
      path: '/vet/search'
      fullPath: '/vet/search'
      preLoaderRoute: typeof VetSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/reports': {
      id: '/vet/reports'
      path: '/vet/reports'
      fullPath: '/vet/reports'
      preLoaderRoute: typeof VetReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/hotel': {
      id: '/vet/hotel'
      path: '/vet/hotel'
      fullPath: '/vet/hotel'
      preLoaderRoute: typeof VetHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/add-pet': {
      id: '/vet/add-pet'
      path: '/vet/add-pet'
      fullPath: '/vet/add-pet'
      preLoaderRoute: typeof VetAddPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/search': {
      id: '/hotel/search'
      path: '/hotel/search'
      fullPath: '/hotel/search'
      preLoaderRoute: typeof HotelSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/reports': {
      id: '/hotel/reports'
      path: '/hotel/reports'
      fullPath: '/hotel/reports'
      preLoaderRoute: typeof HotelReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/history': {
      id: '/hotel/history'
      path: '/hotel/history'
      fullPath: '/hotel/history'
      preLoaderRoute: typeof HotelHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/guests': {
      id: '/hotel/guests'
      path: '/hotel/guests'
      fullPath: '/hotel/guests'
      preLoaderRoute: typeof HotelGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/add-pet': {
      id: '/hotel/add-pet'
      path: '/hotel/add-pet'
      fullPath: '/hotel/add-pet'
      preLoaderRoute: typeof HotelAddPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/$bookingId': {
      id: '/hotel/$bookingId'
      path: '/hotel/$bookingId'
      fullPath: '/hotel/$bookingId'
      preLoaderRoute: typeof HotelBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/reports': {
      id: '/clinic/reports'
      path: '/clinic/reports'
      fullPath: '/clinic/reports'
      preLoaderRoute: typeof ClinicReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/species': {
      id: '/api/species'
      path: '/api/species'
      fullPath: '/api/species'
      preLoaderRoute: typeof ApiSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pets': {
      id: '/api/pets'
      path: '/api/pets'
      fullPath: '/api/pets'
      preLoaderRoute: typeof ApiPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel-bookings': {
      id: '/api/hotel-bookings'
      path: '/api/hotel-bookings'
      fullPath: '/api/hotel-bookings'
      preLoaderRoute: typeof ApiHotelBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/new/': {
      id: '/hotel/new/'
      path: '/hotel/new'
      fullPath: '/hotel/new/'
      preLoaderRoute: typeof HotelNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/visits/$visitId': {
      id: '/vet/visits/$visitId'
      path: '/vet/visits/$visitId'
      fullPath: '/vet/visits/$visitId'
      preLoaderRoute: typeof VetVisitsVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/hotel/$bookingId': {
      id: '/vet/hotel/$bookingId'
      path: '/$bookingId'
      fullPath: '/vet/hotel/$bookingId'
      preLoaderRoute: typeof VetHotelBookingIdRouteImport
      parentRoute: typeof VetHotelRoute
    }
    '/vet/daily-reports/$reportId': {
      id: '/vet/daily-reports/$reportId'
      path: '/vet/daily-reports/$reportId'
      fullPath: '/vet/daily-reports/$reportId'
      preLoaderRoute: typeof VetDailyReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/vet/$token': {
      id: '/share/vet/$token'
      path: '/share/vet/$token'
      fullPath: '/share/vet/$token'
      preLoaderRoute: typeof ShareVetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/hotel/$token': {
      id: '/share/hotel/$token'
      path: '/share/hotel/$token'
      fullPath: '/share/hotel/$token'
      preLoaderRoute: typeof ShareHotelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/edit': {
      id: '/pets/$petId/edit'
      path: '/edit'
      fullPath: '/pets/$petId/edit'
      preLoaderRoute: typeof PetsPetIdEditRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/hotel/new/$petId': {
      id: '/hotel/new/$petId'
      path: '/hotel/new/$petId'
      fullPath: '/hotel/new/$petId'
      preLoaderRoute: typeof HotelNewPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visits/$visitId': {
      id: '/api/visits/$visitId'
      path: '/$visitId'
      fullPath: '/api/visits/$visitId'
      preLoaderRoute: typeof ApiVisitsVisitIdRouteImport
      parentRoute: typeof ApiVisitsRoute
    }
    '/api/users/register-for-vet': {
      id: '/api/users/register-for-vet'
      path: '/api/users/register-for-vet'
      fullPath: '/api/users/register-for-vet'
      preLoaderRoute: typeof ApiUsersRegisterForVetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/register-for-hotel': {
      id: '/api/users/register-for-hotel'
      path: '/api/users/register-for-hotel'
      fullPath: '/api/users/register-for-hotel'
      preLoaderRoute: typeof ApiUsersRegisterForHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/phone-check': {
      id: '/api/users/phone-check'
      path: '/api/users/phone-check'
      fullPath: '/api/users/phone-check'
      preLoaderRoute: typeof ApiUsersPhoneCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/pet': {
      id: '/api/search/pet'
      path: '/api/search/pet'
      fullPath: '/api/search/pet'
      preLoaderRoute: typeof ApiSearchPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/owner': {
      id: '/api/search/owner'
      path: '/api/search/owner'
      fullPath: '/api/search/owner'
      preLoaderRoute: typeof ApiSearchOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/api/products/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pets/$petId': {
      id: '/api/pets/$petId'
      path: '/$petId'
      fullPath: '/api/pets/$petId'
      preLoaderRoute: typeof ApiPetsPetIdRouteImport
      parentRoute: typeof ApiPetsRoute
    }
    '/api/hotel/standalone': {
      id: '/api/hotel/standalone'
      path: '/api/hotel/standalone'
      fullPath: '/api/hotel/standalone'
      preLoaderRoute: typeof ApiHotelStandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/$bookingId': {
      id: '/api/hotel/$bookingId'
      path: '/api/hotel/$bookingId'
      fullPath: '/api/hotel/$bookingId'
      preLoaderRoute: typeof ApiHotelBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel-bookings/$bookingId': {
      id: '/api/hotel-bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/api/hotel-bookings/$bookingId'
      preLoaderRoute: typeof ApiHotelBookingsBookingIdRouteImport
      parentRoute: typeof ApiHotelBookingsRoute
    }
    '/api/daily-reports/$reportId': {
      id: '/api/daily-reports/$reportId'
      path: '/api/daily-reports/$reportId'
      fullPath: '/api/daily-reports/$reportId'
      preLoaderRoute: typeof ApiDailyReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clinic/mine': {
      id: '/api/clinic/mine'
      path: '/api/clinic/mine'
      fullPath: '/api/clinic/mine'
      preLoaderRoute: typeof ApiClinicMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clinic/$clinicId': {
      id: '/api/clinic/$clinicId'
      path: '/api/clinic/$clinicId'
      fullPath: '/api/clinic/$clinicId'
      preLoaderRoute: typeof ApiClinicClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/visits/new/$petId': {
      id: '/vet/visits/new/$petId'
      path: '/vet/visits/new/$petId'
      fullPath: '/vet/visits/new/$petId'
      preLoaderRoute: typeof VetVisitsNewPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/hotel/new/$petId': {
      id: '/vet/hotel/new/$petId'
      path: '/new/$petId'
      fullPath: '/vet/hotel/new/$petId'
      preLoaderRoute: typeof VetHotelNewPetIdRouteImport
      parentRoute: typeof VetHotelRoute
    }
    '/api/visits/$visitId/share': {
      id: '/api/visits/$visitId/share'
      path: '/share'
      fullPath: '/api/visits/$visitId/share'
      preLoaderRoute: typeof ApiVisitsVisitIdShareRouteImport
      parentRoute: typeof ApiVisitsVisitIdRoute
    }
    '/api/visits/$visitId/daily-reports': {
      id: '/api/visits/$visitId/daily-reports'
      path: '/daily-reports'
      fullPath: '/api/visits/$visitId/daily-reports'
      preLoaderRoute: typeof ApiVisitsVisitIdDailyReportsRouteImport
      parentRoute: typeof ApiVisitsVisitIdRoute
    }
    '/api/users/me/register-pet-owner': {
      id: '/api/users/me/register-pet-owner'
      path: '/register-pet-owner'
      fullPath: '/api/users/me/register-pet-owner'
      preLoaderRoute: typeof ApiUsersMeRegisterPetOwnerRouteImport
      parentRoute: typeof ApiUsersMeRoute
    }
    '/api/share/vet/$token': {
      id: '/api/share/vet/$token'
      path: '/api/share/vet/$token'
      fullPath: '/api/share/vet/$token'
      preLoaderRoute: typeof ApiShareVetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/hotel/$token': {
      id: '/api/share/hotel/$token'
      path: '/api/share/hotel/$token'
      fullPath: '/api/share/hotel/$token'
      preLoaderRoute: typeof ApiShareHotelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pets/$petId/vaccinations': {
      id: '/api/pets/$petId/vaccinations'
      path: '/vaccinations'
      fullPath: '/api/pets/$petId/vaccinations'
      preLoaderRoute: typeof ApiPetsPetIdVaccinationsRouteImport
      parentRoute: typeof ApiPetsPetIdRoute
    }
    '/api/pets/$petId/health-events': {
      id: '/api/pets/$petId/health-events'
      path: '/health-events'
      fullPath: '/api/pets/$petId/health-events'
      preLoaderRoute: typeof ApiPetsPetIdHealthEventsRouteImport
      parentRoute: typeof ApiPetsPetIdRoute
    }
    '/api/hotel/$bookingId/share': {
      id: '/api/hotel/$bookingId/share'
      path: '/share'
      fullPath: '/api/hotel/$bookingId/share'
      preLoaderRoute: typeof ApiHotelBookingIdShareRouteImport
      parentRoute: typeof ApiHotelBookingIdRoute
    }
    '/api/hotel/$bookingId/logs': {
      id: '/api/hotel/$bookingId/logs'
      path: '/logs'
      fullPath: '/api/hotel/$bookingId/logs'
      preLoaderRoute: typeof ApiHotelBookingIdLogsRouteImport
      parentRoute: typeof ApiHotelBookingIdRoute
    }
    '/api/hotel-bookings/$bookingId/daily-logs': {
      id: '/api/hotel-bookings/$bookingId/daily-logs'
      path: '/daily-logs'
      fullPath: '/api/hotel-bookings/$bookingId/daily-logs'
      preLoaderRoute: typeof ApiHotelBookingsBookingIdDailyLogsRouteImport
      parentRoute: typeof ApiHotelBookingsBookingIdRoute
    }
    '/api/clinic/$clinicId/staff': {
      id: '/api/clinic/$clinicId/staff'
      path: '/staff'
      fullPath: '/api/clinic/$clinicId/staff'
      preLoaderRoute: typeof ApiClinicClinicIdStaffRouteImport
      parentRoute: typeof ApiClinicClinicIdRoute
    }
    '/api/clinic/$clinicId/products': {
      id: '/api/clinic/$clinicId/products'
      path: '/products'
      fullPath: '/api/clinic/$clinicId/products'
      preLoaderRoute: typeof ApiClinicClinicIdProductsRouteImport
      parentRoute: typeof ApiClinicClinicIdRoute
    }
    '/api/pets/$petId/vaccinations/$vaccinationId': {
      id: '/api/pets/$petId/vaccinations/$vaccinationId'
      path: '/$vaccinationId'
      fullPath: '/api/pets/$petId/vaccinations/$vaccinationId'
      preLoaderRoute: typeof ApiPetsPetIdVaccinationsVaccinationIdRouteImport
      parentRoute: typeof ApiPetsPetIdVaccinationsRoute
    }
    '/api/pets/$petId/health-events/$eventId': {
      id: '/api/pets/$petId/health-events/$eventId'
      path: '/$eventId'
      fullPath: '/api/pets/$petId/health-events/$eventId'
      preLoaderRoute: typeof ApiPetsPetIdHealthEventsEventIdRouteImport
      parentRoute: typeof ApiPetsPetIdHealthEventsRoute
    }
    '/api/hotel/clinic/$clinicId/bookings': {
      id: '/api/hotel/clinic/$clinicId/bookings'
      path: '/api/hotel/clinic/$clinicId/bookings'
      fullPath: '/api/hotel/clinic/$clinicId/bookings'
      preLoaderRoute: typeof ApiHotelClinicClinicIdBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/$hotelId/reports/summary': {
      id: '/api/hotel/$hotelId/reports/summary'
      path: '/api/hotel/$hotelId/reports/summary'
      fullPath: '/api/hotel/$hotelId/reports/summary'
      preLoaderRoute: typeof ApiHotelHotelIdReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/$bookingId/logs/$logId': {
      id: '/api/hotel/$bookingId/logs/$logId'
      path: '/$logId'
      fullPath: '/api/hotel/$bookingId/logs/$logId'
      preLoaderRoute: typeof ApiHotelBookingIdLogsLogIdRouteImport
      parentRoute: typeof ApiHotelBookingIdLogsRoute
    }
    '/api/hotel-bookings/$bookingId/daily-logs/$logId': {
      id: '/api/hotel-bookings/$bookingId/daily-logs/$logId'
      path: '/$logId'
      fullPath: '/api/hotel-bookings/$bookingId/daily-logs/$logId'
      preLoaderRoute: typeof ApiHotelBookingsBookingIdDailyLogsLogIdRouteImport
      parentRoute: typeof ApiHotelBookingsBookingIdDailyLogsRoute
    }
    '/api/clinic/$clinicId/staff/$staffId': {
      id: '/api/clinic/$clinicId/staff/$staffId'
      path: '/$staffId'
      fullPath: '/api/clinic/$clinicId/staff/$staffId'
      preLoaderRoute: typeof ApiClinicClinicIdStaffStaffIdRouteImport
      parentRoute: typeof ApiClinicClinicIdStaffRoute
    }
    '/api/clinic/$clinicId/reports/summary': {
      id: '/api/clinic/$clinicId/reports/summary'
      path: '/reports/summary'
      fullPath: '/api/clinic/$clinicId/reports/summary'
      preLoaderRoute: typeof ApiClinicClinicIdReportsSummaryRouteImport
      parentRoute: typeof ApiClinicClinicIdRoute
    }
    '/api/clinic/$clinicId/reports/stats': {
      id: '/api/clinic/$clinicId/reports/stats'
      path: '/reports/stats'
      fullPath: '/api/clinic/$clinicId/reports/stats'
      preLoaderRoute: typeof ApiClinicClinicIdReportsStatsRouteImport
      parentRoute: typeof ApiClinicClinicIdRoute
    }
  }
}

interface ApiHotelBookingsBookingIdDailyLogsRouteChildren {
  ApiHotelBookingsBookingIdDailyLogsLogIdRoute: typeof ApiHotelBookingsBookingIdDailyLogsLogIdRoute
}

const ApiHotelBookingsBookingIdDailyLogsRouteChildren: ApiHotelBookingsBookingIdDailyLogsRouteChildren =
  {
    ApiHotelBookingsBookingIdDailyLogsLogIdRoute:
      ApiHotelBookingsBookingIdDailyLogsLogIdRoute,
  }

const ApiHotelBookingsBookingIdDailyLogsRouteWithChildren =
  ApiHotelBookingsBookingIdDailyLogsRoute._addFileChildren(
    ApiHotelBookingsBookingIdDailyLogsRouteChildren,
  )

interface ApiHotelBookingsBookingIdRouteChildren {
  ApiHotelBookingsBookingIdDailyLogsRoute: typeof ApiHotelBookingsBookingIdDailyLogsRouteWithChildren
}

const ApiHotelBookingsBookingIdRouteChildren: ApiHotelBookingsBookingIdRouteChildren =
  {
    ApiHotelBookingsBookingIdDailyLogsRoute:
      ApiHotelBookingsBookingIdDailyLogsRouteWithChildren,
  }

const ApiHotelBookingsBookingIdRouteWithChildren =
  ApiHotelBookingsBookingIdRoute._addFileChildren(
    ApiHotelBookingsBookingIdRouteChildren,
  )

interface ApiHotelBookingsRouteChildren {
  ApiHotelBookingsBookingIdRoute: typeof ApiHotelBookingsBookingIdRouteWithChildren
}

const ApiHotelBookingsRouteChildren: ApiHotelBookingsRouteChildren = {
  ApiHotelBookingsBookingIdRoute: ApiHotelBookingsBookingIdRouteWithChildren,
}

const ApiHotelBookingsRouteWithChildren =
  ApiHotelBookingsRoute._addFileChildren(ApiHotelBookingsRouteChildren)

interface ApiPetsPetIdHealthEventsRouteChildren {
  ApiPetsPetIdHealthEventsEventIdRoute: typeof ApiPetsPetIdHealthEventsEventIdRoute
}

const ApiPetsPetIdHealthEventsRouteChildren: ApiPetsPetIdHealthEventsRouteChildren =
  {
    ApiPetsPetIdHealthEventsEventIdRoute: ApiPetsPetIdHealthEventsEventIdRoute,
  }

const ApiPetsPetIdHealthEventsRouteWithChildren =
  ApiPetsPetIdHealthEventsRoute._addFileChildren(
    ApiPetsPetIdHealthEventsRouteChildren,
  )

interface ApiPetsPetIdVaccinationsRouteChildren {
  ApiPetsPetIdVaccinationsVaccinationIdRoute: typeof ApiPetsPetIdVaccinationsVaccinationIdRoute
}

const ApiPetsPetIdVaccinationsRouteChildren: ApiPetsPetIdVaccinationsRouteChildren =
  {
    ApiPetsPetIdVaccinationsVaccinationIdRoute:
      ApiPetsPetIdVaccinationsVaccinationIdRoute,
  }

const ApiPetsPetIdVaccinationsRouteWithChildren =
  ApiPetsPetIdVaccinationsRoute._addFileChildren(
    ApiPetsPetIdVaccinationsRouteChildren,
  )

interface ApiPetsPetIdRouteChildren {
  ApiPetsPetIdHealthEventsRoute: typeof ApiPetsPetIdHealthEventsRouteWithChildren
  ApiPetsPetIdVaccinationsRoute: typeof ApiPetsPetIdVaccinationsRouteWithChildren
}

const ApiPetsPetIdRouteChildren: ApiPetsPetIdRouteChildren = {
  ApiPetsPetIdHealthEventsRoute: ApiPetsPetIdHealthEventsRouteWithChildren,
  ApiPetsPetIdVaccinationsRoute: ApiPetsPetIdVaccinationsRouteWithChildren,
}

const ApiPetsPetIdRouteWithChildren = ApiPetsPetIdRoute._addFileChildren(
  ApiPetsPetIdRouteChildren,
)

interface ApiPetsRouteChildren {
  ApiPetsPetIdRoute: typeof ApiPetsPetIdRouteWithChildren
}

const ApiPetsRouteChildren: ApiPetsRouteChildren = {
  ApiPetsPetIdRoute: ApiPetsPetIdRouteWithChildren,
}

const ApiPetsRouteWithChildren =
  ApiPetsRoute._addFileChildren(ApiPetsRouteChildren)

interface ApiVisitsVisitIdRouteChildren {
  ApiVisitsVisitIdDailyReportsRoute: typeof ApiVisitsVisitIdDailyReportsRoute
  ApiVisitsVisitIdShareRoute: typeof ApiVisitsVisitIdShareRoute
}

const ApiVisitsVisitIdRouteChildren: ApiVisitsVisitIdRouteChildren = {
  ApiVisitsVisitIdDailyReportsRoute: ApiVisitsVisitIdDailyReportsRoute,
  ApiVisitsVisitIdShareRoute: ApiVisitsVisitIdShareRoute,
}

const ApiVisitsVisitIdRouteWithChildren =
  ApiVisitsVisitIdRoute._addFileChildren(ApiVisitsVisitIdRouteChildren)

interface ApiVisitsRouteChildren {
  ApiVisitsVisitIdRoute: typeof ApiVisitsVisitIdRouteWithChildren
}

const ApiVisitsRouteChildren: ApiVisitsRouteChildren = {
  ApiVisitsVisitIdRoute: ApiVisitsVisitIdRouteWithChildren,
}

const ApiVisitsRouteWithChildren = ApiVisitsRoute._addFileChildren(
  ApiVisitsRouteChildren,
)

interface PetsPetIdRouteChildren {
  PetsPetIdEditRoute: typeof PetsPetIdEditRoute
}

const PetsPetIdRouteChildren: PetsPetIdRouteChildren = {
  PetsPetIdEditRoute: PetsPetIdEditRoute,
}

const PetsPetIdRouteWithChildren = PetsPetIdRoute._addFileChildren(
  PetsPetIdRouteChildren,
)

interface VetHotelRouteChildren {
  VetHotelBookingIdRoute: typeof VetHotelBookingIdRoute
  VetHotelNewPetIdRoute: typeof VetHotelNewPetIdRoute
}

const VetHotelRouteChildren: VetHotelRouteChildren = {
  VetHotelBookingIdRoute: VetHotelBookingIdRoute,
  VetHotelNewPetIdRoute: VetHotelNewPetIdRoute,
}

const VetHotelRouteWithChildren = VetHotelRoute._addFileChildren(
  VetHotelRouteChildren,
)

interface ApiClinicClinicIdStaffRouteChildren {
  ApiClinicClinicIdStaffStaffIdRoute: typeof ApiClinicClinicIdStaffStaffIdRoute
}

const ApiClinicClinicIdStaffRouteChildren: ApiClinicClinicIdStaffRouteChildren =
  {
    ApiClinicClinicIdStaffStaffIdRoute: ApiClinicClinicIdStaffStaffIdRoute,
  }

const ApiClinicClinicIdStaffRouteWithChildren =
  ApiClinicClinicIdStaffRoute._addFileChildren(
    ApiClinicClinicIdStaffRouteChildren,
  )

interface ApiClinicClinicIdRouteChildren {
  ApiClinicClinicIdProductsRoute: typeof ApiClinicClinicIdProductsRoute
  ApiClinicClinicIdStaffRoute: typeof ApiClinicClinicIdStaffRouteWithChildren
  ApiClinicClinicIdReportsStatsRoute: typeof ApiClinicClinicIdReportsStatsRoute
  ApiClinicClinicIdReportsSummaryRoute: typeof ApiClinicClinicIdReportsSummaryRoute
}

const ApiClinicClinicIdRouteChildren: ApiClinicClinicIdRouteChildren = {
  ApiClinicClinicIdProductsRoute: ApiClinicClinicIdProductsRoute,
  ApiClinicClinicIdStaffRoute: ApiClinicClinicIdStaffRouteWithChildren,
  ApiClinicClinicIdReportsStatsRoute: ApiClinicClinicIdReportsStatsRoute,
  ApiClinicClinicIdReportsSummaryRoute: ApiClinicClinicIdReportsSummaryRoute,
}

const ApiClinicClinicIdRouteWithChildren =
  ApiClinicClinicIdRoute._addFileChildren(ApiClinicClinicIdRouteChildren)

interface ApiHotelBookingIdLogsRouteChildren {
  ApiHotelBookingIdLogsLogIdRoute: typeof ApiHotelBookingIdLogsLogIdRoute
}

const ApiHotelBookingIdLogsRouteChildren: ApiHotelBookingIdLogsRouteChildren = {
  ApiHotelBookingIdLogsLogIdRoute: ApiHotelBookingIdLogsLogIdRoute,
}

const ApiHotelBookingIdLogsRouteWithChildren =
  ApiHotelBookingIdLogsRoute._addFileChildren(
    ApiHotelBookingIdLogsRouteChildren,
  )

interface ApiHotelBookingIdRouteChildren {
  ApiHotelBookingIdLogsRoute: typeof ApiHotelBookingIdLogsRouteWithChildren
  ApiHotelBookingIdShareRoute: typeof ApiHotelBookingIdShareRoute
}

const ApiHotelBookingIdRouteChildren: ApiHotelBookingIdRouteChildren = {
  ApiHotelBookingIdLogsRoute: ApiHotelBookingIdLogsRouteWithChildren,
  ApiHotelBookingIdShareRoute: ApiHotelBookingIdShareRoute,
}

const ApiHotelBookingIdRouteWithChildren =
  ApiHotelBookingIdRoute._addFileChildren(ApiHotelBookingIdRouteChildren)

interface ApiUsersMeRouteChildren {
  ApiUsersMeRegisterPetOwnerRoute: typeof ApiUsersMeRegisterPetOwnerRoute
}

const ApiUsersMeRouteChildren: ApiUsersMeRouteChildren = {
  ApiUsersMeRegisterPetOwnerRoute: ApiUsersMeRegisterPetOwnerRoute,
}

const ApiUsersMeRouteWithChildren = ApiUsersMeRoute._addFileChildren(
  ApiUsersMeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHotelBookingsRoute: ApiHotelBookingsRouteWithChildren,
  ApiPetsRoute: ApiPetsRouteWithChildren,
  ApiSpeciesRoute: ApiSpeciesRoute,
  ApiVisitsRoute: ApiVisitsRouteWithChildren,
  ClinicReportsRoute: ClinicReportsRoute,
  HotelBookingIdRoute: HotelBookingIdRoute,
  HotelAddPetRoute: HotelAddPetRoute,
  HotelGuestsRoute: HotelGuestsRoute,
  HotelHistoryRoute: HotelHistoryRoute,
  HotelReportsRoute: HotelReportsRoute,
  HotelSearchRoute: HotelSearchRoute,
  PetsPetIdRoute: PetsPetIdRouteWithChildren,
  PetsNewRoute: PetsNewRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  VetAddPetRoute: VetAddPetRoute,
  VetHotelRoute: VetHotelRouteWithChildren,
  VetReportsRoute: VetReportsRoute,
  VetSearchRoute: VetSearchRoute,
  ClinicIndexRoute: ClinicIndexRoute,
  HotelIndexRoute: HotelIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PetsIndexRoute: PetsIndexRoute,
  VetIndexRoute: VetIndexRoute,
  ApiClinicClinicIdRoute: ApiClinicClinicIdRouteWithChildren,
  ApiClinicMineRoute: ApiClinicMineRoute,
  ApiDailyReportsReportIdRoute: ApiDailyReportsReportIdRoute,
  ApiHotelBookingIdRoute: ApiHotelBookingIdRouteWithChildren,
  ApiHotelStandaloneRoute: ApiHotelStandaloneRoute,
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
  ApiSearchOwnerRoute: ApiSearchOwnerRoute,
  ApiSearchPetRoute: ApiSearchPetRoute,
  ApiUsersMeRoute: ApiUsersMeRouteWithChildren,
  ApiUsersPhoneCheckRoute: ApiUsersPhoneCheckRoute,
  ApiUsersRegisterForHotelRoute: ApiUsersRegisterForHotelRoute,
  ApiUsersRegisterForVetRoute: ApiUsersRegisterForVetRoute,
  HotelNewPetIdRoute: HotelNewPetIdRoute,
  ShareHotelTokenRoute: ShareHotelTokenRoute,
  ShareVetTokenRoute: ShareVetTokenRoute,
  VetDailyReportsReportIdRoute: VetDailyReportsReportIdRoute,
  VetVisitsVisitIdRoute: VetVisitsVisitIdRoute,
  HotelNewIndexRoute: HotelNewIndexRoute,
  ApiShareHotelTokenRoute: ApiShareHotelTokenRoute,
  ApiShareVetTokenRoute: ApiShareVetTokenRoute,
  VetVisitsNewPetIdRoute: VetVisitsNewPetIdRoute,
  ApiHotelHotelIdReportsSummaryRoute: ApiHotelHotelIdReportsSummaryRoute,
  ApiHotelClinicClinicIdBookingsRoute: ApiHotelClinicClinicIdBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
